server:
  port: 10010
spring:
  application:
    name: pet-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  add-host-header: true
  prefix: /api #路由路径的前缀
  routes:
    user-service: /user/** #用户服务的映射路径
    pet-service: /pet/** #商品服务的映射路径
#    system-service: /system/**
